laravel/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('frontend.pages.home.index');
})->name('homepage');

Route::get('about', function () {
    return view('frontend.pages.about.index');
})->name('about');

Route::get('items', function () {
    return view('frontend.pages.products.index');
})->name('product');

Route::get('store', function () {
    return view('frontend.pages.store.index');
})->name('store');

Route::get('home', 'Backend\HomeController@index')->name('home');

Auth::routes();

Route::get('dashboard', 'Backend\HomeController@index')->name('dashboard');

Route::resource('cashier', 'Backend\CashierController')->middleware('auth');

Route::resource('products', 'Backend\ProductController')->middleware('auth');

Route::resource('inventory', 'Backend\InventoryController')->middleware('auth')->parameters(['inventory'=>'product']);

Route::resource('categories', 'Backend\ProductCategoryController')->middleware('auth');

Route::resource('users', 'Backend\UserController')->middleware('auth');

Route::resource('orders', 'Backend\OrderController')->middleware('auth');

Route::resource('branches', 'Backend\BranchController')->middleware('auth');

Route::resource('transactions', 'Backend\TransactionController')->middleware('auth');

Route::get('users-search', 'Backend\UserController@search')->name('users.search');

laravel/resources/views/backend/pages/categories/create.blade.php
@extends('backend.layouts.app')

@section('content')
<div class="card">
    <div class="card-header">Add Category</div>
    <div class="card-body">
            {!! Form::open(['route' => 'categories.store', 'method' => 'post', 'enctype' => 'multipart/form-data']) !!}
            <div class="form-row">
                <div class="form-group col-5">
                    {!! Form::label('name', 'Category Name') !!}
                    {!! Form::text('name', null, ['class' => 'form-control', 'required']) !!}
                </div>
                <div class="form-group col-5">
                    {!! Form::label('with_sizes', 'With Sizes') !!}
                    {!! Form::checkbox('with_sizes', null, ['class' => 'form-control', 'required']) !!}
                </div>
            </div>
            <button type="submit" class ="btn btn-primary" onclick="blur()">Save</button>
            {!! Form::close() !!}
        </div>
    </div>
</div> 
@endsection 
@section('js')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
    <script>
    $(".cat_sect").select2({
        placeholder : "Choose a tag",
        maximumSelectionLength: 1
    });
    </script>
@endsection

laravel/resources/views/backend/pages/categories/edit.blade.php
@extends('backend.layouts.app')

@section('content')
<div class="card">
    <div class="card-header">Add Category</div>
    <div class="card-body">
            {!! Form::model($category, ['route' => ['categories.update', $category->id], 'method' => 'PUT', 'enctype' => 'multipart/form-data']) !!}
            <div class="form-row">
                <div class="form-group col">
                    {!! Form::label('name', 'Category Name') !!}
                    {!! Form::text('name', null, ['class' => 'form-control', 'required']) !!}
                </div>
                <div class="col"></div>
            </div>
            <button type="submit" class ="btn btn-primary" onclick="blur()">Save</button>
            {!! Form::close() !!}
        </div>
    </div>
</div> 
@endsection 
@section('js')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
    <script>
    $(".cat_sect").select2({
        placeholder : "Choose a tag",
        maximumSelectionLength: 1
    });
    </script>
@endsection

laravel/resources/views/backend/pages/categories/index.blade.php
@extends('backend.layouts.app')

@section('css')
    <style>
        thead > tr > td{
            font-weight: bold;
        }
        tbody > tr > td > img{
            width: 40px;;
        }
    </style>
@endsection
@section('content')
<div class="card">
    <div class="card-header">Categories</div>
    <div class="card-body">
       <a href="{{ route('categories.create') }}" class="btn btn-primary" onclick="blur()">Add Category</a>
       <br><br>
       @if($categories->isNotEmpty())
       <div class="table">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <td>Category Name</td>
                    </tr>
                </thead>
                <tbody>
                    @foreach($categories as $category)
                    <tr>
                        <td>{{ $category->name }}</td>
                        <td>
                            <a href="{{route('categories.edit', $category->id)}}"><button type="button" class="btn btn-info">Edit</button></a>
                            {!!Form::open(['route' => ['categories.destroy', $category->id], 'method' => 'POST', 'class' => 'pull-right'])!!}
                            {{Form::hidden('_method', 'DELETE')}}
                            {{Form::submit('Delete', ['class' => 'btn btn-danger', 'onclick'=> 'return confirm("Are you sure you want to delete?")'])}}
                            {!!Form::close()!!}
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        @else
        <center>
            <h2>No categories yet...</h2>
        </center>
        @endif
    </div>
</div> 
@endsection